### PR TITLE
add dnx infrastructure

### PR DESCRIPTION
**Pull request by qooroo**
This is setup to run with dnx on full clr and mono (tested on ubuntu 14.04). CoreClr stuff to come soon.

### CODE REVIEW

**Comment by qooroo** [comment]
for https://github.com/LeeCampbell/HdrHistogram.NET/issues/31

**Comment by LeeCampbell** [comment]
Can we gitignore the lock.json files.
Looking fwd to the dnx5 stuff

**Comment by LeeCampbell** [comment]
Is there any further work required on this?

**Comment by qooroo** [comment]
Didn't you get this working on coreclr? If so then that makes this PR redundant and I'll close it.

**Comment by LeeCampbell** [comment]
TBH, I dont really know what is required to get a nuget artefact produced that supports .NET 4.6, Universal Apps, Mono and Core CLR. I would like it if I could create a package that supports all reasonably new platforms (4.5+?)

**Comment by qooroo** [comment]
Yup. Anyway I think this PR is obsolete now that RC2 is out. Gonna close it.

**Pull request closed without merging**
